### ISSUE TITLE
Animation customization

### ISSUE THREAD

**Issue by ivankaptue** [gabriel-TheCode/AestheticDialogs#11]
The user will be able to choose their preferred animation style. (FadeIn/FadeOut, SlideInLeft, etc)

**Comment by gabriel-TheCode** [comment]
Noted for the next release. Thank you for the feedback

**Comment by ivankaptue** [comment]
Can I contribute to project ? I'm Ivan Kaptue from LinkedIn comment ;)

**Comment by gabriel-TheCode** [comment]
Nice, Sure @ivankaptue ! Just make a pull request on dev

**Comment by gabriel-TheCode** [comment]
#15 Resolved !
