### ISSUE TITLE
Emotion dialog not high enough

### ISSUE THREAD

**Issue by Lorincz** [gabriel-TheCode/AestheticDialogs#16]
Hey,

Unfortunately the emotion dialog is not high enough, The message is not visible properly. Only the top of the text.

Regards,
Isti

**Comment by gabriel-TheCode** [comment]
Hey @Lorincz , can you provide a screenshot please, so I can resolve this issue efficiently. Thanks

**Comment by gabriel-TheCode** [comment]
Closed due to inactivity, please reopen if needed.
