### ISSUE TITLE
Resource Linking Issue

### ISSUE THREAD

**Issue by walkmn** [gabriel-TheCode/AestheticDialogs#18]
Hey, I found some issue. When I've added:
> implementation 'com.github.gabriel-TheCode:AestheticDialogs:1.3.4'

I'm getting error messages like resources not found (colors/...)

Could you please move these colors:
https://github.com/gabriel-TheCode/AestheticDialogs/blob/master/app/src/main/res/values/colors.xml (from example app module)
to library level?
https://github.com/gabriel-TheCode/AestheticDialogs/tree/master/aestheticdialogs/src/main/res

Thanks!

**Comment by gabriel-TheCode** [comment]
Thank you for your feedback @walkmn. 

#19 Resolved

Happy coding. 👨🏽‍💻
