### ISSUE TITLE
Text is cut

### ISSUE THREAD

**Issue by Dave181295** [gabriel-TheCode/AestheticDialogs#20]
Merci ! thanks for your awesome library, when I put a long message  it's cut, can you fix it ?

![IMG_0948](https://user-images.githubusercontent.com/76634618/110404889-5d0d6a80-8088-11eb-97fd-0d9aa31e3255.png)

**Comment by gabriel-TheCode** [comment]
Thanks for your feedback @Dave181295, the message text will be update to 3 lines in the next release.

**Comment by gabriel-TheCode** [comment]
Resolved #21. [New release](https://github.com/gabriel-TheCode/AestheticDialogs/releases/tag/1.3.6)
