### ISSUE TITLE
setOnClickListener problem in Java

### ISSUE THREAD

**Issue by skreenr** [gabriel-TheCode/AestheticDialogs#24]
I am working in Java and have problem when trying to use setOnClickListener 
Without it everything works in A-Studio, like 
![Gab kt ok](https://user-images.githubusercontent.com/57162684/147441910-aee7575f-6c42-45ac-9826-4d8f6d31c0e3.png)

yet when adding setOnClickListener  here is what I get 

![Gab kt](https://user-images.githubusercontent.com/57162684/147442004-1265ea6e-0253-43a4-8b51-04b715db1a5b.png)

Please advise on proper syntax for Java

**Comment by BoredOwlG** [comment]
Use it the same way, you handle all setOnClickListener:

![Screenshot from 2022-05-08 10-22-29](https://user-images.githubusercontent.com/102754804/167287939-b6d26473-4802-49c5-9375-b7811f28bec2.png)

Edit:
Bottom is the same, just with lambda
