### ISSUE TITLE
Add Onlistener 

### ISSUE THREAD

**Issue by anonym2** [gabriel-TheCode/AestheticDialogs#4]
Hi Sir  I really like you library but can you add onlistener propreties  ? I would like to use your library for going on another activity when my users  click on the Ok button

**Comment by gabriel-TheCode** [comment]
Thank you for the feedback. I will add this feature in the next update.  You will be notified as soon as possible. Best regards

**Comment by gabriel-TheCode** [comment]
Added in latest release #8
